import { NextRequest, NextResponse } from 'next/server'
import { createServiceClient } from '@/lib/supabase'
import { jsPDF } from 'jspdf'

export const dynamic = 'force-dynamic'

export async function GET(req: NextRequest) {
  const lessonId = req.nextUrl.searchParams.get('lessonId')
  if (!lessonId) return NextResponse.json({ error: 'lessonId required' }, { status: 400 })

  const supabase = createServiceClient()

  const { data: lesson } = await supabase
    .from('lessons')
    .select('*, courses(title)')
    .eq('id', lessonId)
    .single()

  if (!lesson) return NextResponse.json({ error: 'Lesson not found' }, { status: 404 })

  const course = lesson.courses as { title: string } | null
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  const margin = 15
  const contentWidth = pageWidth - margin * 2
  let y = margin

  function checkPage(needed: number) {
    if (y + needed > 280) {
      doc.addPage()
      y = margin
    }
  }

  function addTitle(text: string) {
    checkPage(14)
    doc.setFontSize(18)
    doc.setFont('helvetica', 'bold')
    doc.text(text, margin, y)
    y += 10
  }

  function addSubtitle(text: string) {
    checkPage(10)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.text(text, margin, y)
    y += 7
  }

  function addBody(text: string) {
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(text, contentWidth)
    for (const line of lines) {
      checkPage(5)
      doc.text(line, margin, y)
      y += 4.5
    }
    y += 3
  }

  function addDivider() {
    checkPage(6)
    y += 2
    doc.setDrawColor(200, 200, 200)
    doc.line(margin, y, pageWidth - margin, y)
    y += 4
  }

  // Header
  addTitle(lesson.title)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(100, 100, 100)
  doc.text(`Course: ${course?.title || 'LessonPilot Course'}`, margin, y)
  y += 5
  doc.text(`Difficulty: ${lesson.difficulty || 'Intermediate'} | Estimated: ${lesson.estimated_minutes || 60} minutes`, margin, y)
  y += 5
  doc.setTextColor(0, 0, 0)
  addDivider()

  // Objective
  if (lesson.objective) {
    addSubtitle('Learning Objective')
    addBody(lesson.objective)
    addDivider()
  }

  // Key Terms
  const keyTerms = Array.isArray(lesson.key_terms)
    ? lesson.key_terms
    : lesson.key_terms ? Object.entries(lesson.key_terms).map(([k, v]) => `${k}: ${v}`) : []

  if (keyTerms.length > 0) {
    addSubtitle('Key Terms')
    for (const term of keyTerms) {
      const termStr = typeof term === 'string' ? term : JSON.stringify(term)
      checkPage(6)
      doc.setFontSize(10)
      doc.setFont('helvetica', 'normal')
      doc.text(`• ${termStr}`, margin + 2, y)
      y += 5
    }
    y += 2
    addDivider()
  }

  // Content summary (first 3000 chars to fit in study guide)
  if (lesson.content) {
    addSubtitle('Lesson Summary')
    // Extract key sections
    const sections = lesson.content.split(/\n*---\n*/)
    for (const section of sections) {
      const trimmed = section.trim()
      if (!trimmed) continue
      const lines = trimmed.split('\n')
      const header = lines[0].trim()

      // Only include summary-worthy sections in PDF
      if (['OVERVIEW', 'LEARNING OBJECTIVES', 'CTS EXAM RELEVANCE', 'STUDY NOTES', 'SUMMARY', 'PRACTICAL ASSIGNMENT'].includes(header)) {
        addSubtitle(header.charAt(0) + header.slice(1).toLowerCase())
        addBody(lines.slice(1).join('\n').trim())
        addDivider()
      } else if (header.match(/^Part \d+/i)) {
        addSubtitle(header)
        // Just first 500 chars of each part for the study guide
        const partContent = lines.slice(1).join('\n').trim()
        addBody(partContent.substring(0, 500) + (partContent.length > 500 ? '...' : ''))
        y += 2
      }
    }
  }

  // Knowledge check (from examples field)
  if (lesson.examples) {
    addSubtitle('Knowledge Check')
    const questions = lesson.examples.split('\n\n').slice(0, 10)
    for (const q of questions) {
      addBody(q.trim())
    }
    addDivider()
  }

  // Recap
  if (lesson.recap) {
    addSubtitle('Key Takeaways')
    addBody(lesson.recap)
  }

  // Footer
  checkPage(15)
  y += 5
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text('Generated by LessonPilot.org — AI-powered teaching that adapts to you', margin, y)

  const pdfBuffer = Buffer.from(doc.output('arraybuffer'))
  const filename = `${lesson.title.replace(/[^a-zA-Z0-9]/g, '_')}_Study_Guide.pdf`

  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
    },
  })
}
